import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import {RxActivityLog} from "react-icons/rx";
// import {FcAcceptDatabase} from "react-icons/fc";
// import {DiAndroid} from "react-icons/di";
import {Text, Spacer} from '@nextui-org/react'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <Text h2>Text text....</Text>
                <Spacer y={1}/>
                <Text size={"$lg"}>
                    Text lg text!
                </Text>
            </div>
        </>
    )
}
